### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by alannt777** [alannt777/AwesomeWindowsDevs#1]

**Comment by alannt777** [comment]
@Aaron-Junker Can you help me with this repo? (if you have the time)

**Comment by Aaron-Junker** [comment]
Yes I can try to help. Is this simply a list why windows is a better developing platform?

**Comment by Aaron-Junker** [comment]
And that with linux isnt such a good point because macos is based of linux

**Comment by alannt777** [comment]
That's why WSL

**Comment by alannt777** [comment]
I have add some more items to the list

**Comment by alannt777** [comment]
> And that with linux isnt such a good point because macos is based of linux

BTW, MacOS is based on Unix, not Linux

**Comment by alannt777** [comment]
Linux itself is based on Unix though

**Comment by alannt777** [comment]
> Yes I can try to help. Is this simply a list why windows is a better developing platform?

**To Clarify**: This is not a repo to tell that Windows is better that MacOS for Development. It JUST says that YOU DON'T NEED a Mac to be a "pro" developer

**Comment by Aaron-Junker** [comment]
Ok and for what usage should this be

**Comment by alannt777** [comment]
It kind of like [awesome lists](https://github.com/topics/awesome)

**Comment by alannt777** [comment]
BTW, if you know C#, you can help me out with [alannt777/LicenseItCLI](https://github.com/alannt777/LicenseItCLI)
